/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRedefinirRouteImport } from './routes/auth.redefinir'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedefinirRoute = AuthRedefinirRouteImport.update({
  id: '/redefinir',
  path: '/redefinir',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/redefinir': typeof AuthRedefinirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/redefinir': typeof AuthRedefinirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/redefinir': typeof AuthRedefinirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cliente'
    | '/quem-somos'
    | '/servicos'
    | '/auth/recuperar'
    | '/auth/redefinir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cliente'
    | '/quem-somos'
    | '/servicos'
    | '/auth/recuperar'
    | '/auth/redefinir'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cliente'
    | '/quem-somos'
    | '/servicos'
    | '/auth/recuperar'
    | '/auth/redefinir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  ClienteRoute: typeof ClienteRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/redefinir': {
      id: '/auth/redefinir'
      path: '/redefinir'
      fullPath: '/auth/redefinir'
      preLoaderRoute: typeof AuthRedefinirRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthRecuperarRoute: typeof AuthRecuperarRoute
  AuthRedefinirRoute: typeof AuthRedefinirRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecuperarRoute: AuthRecuperarRoute,
  AuthRedefinirRoute: AuthRedefinirRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  ClienteRoute: ClienteRoute,
  QuemSomosRoute: QuemSomosRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
